version: "3.9"
services:
  redis:
    image: redis
    restart: unless-stopped
    container_name: 'Redis'
    command: redis-server
    ports:
      - '6379:6379'

  postgres:
    image: postgres:12.4
    restart: unless-stopped
    container_name: 'PostgresDB'
    env_file:
      - docker.env
    ports:
      - 127.0.0.1:5432:5432

  adminer:
    image: adminer:4.7
    restart: always
    container_name: 'dbAdminer'
    ports:
      - 127.0.0.1:8080:8080
