version: '3.1'

services:

  db:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 127.0.0.1:5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080

  redis:
    image: redis
    restart: always
    container_name: 'demo_app_redis'
    command: redis-server
    ports:
      - '6379:6379'

  celery:
    build: .
    container_name: 'demo_app_celery'
    command: celery -A core worker -B
    depends_on:
      - redis