services:
  web:
    image: ticket_locator_img
    container_name: ticket_locator_web
    restart: unless-stopped
    volumes:
      - ../hello_world:/usr/src/app/hello_world
      - ../ticket_locator:/usr/src/app/ticket_locator
    ports:
      - 127.0.0.1:8000:8000
    entrypoint:
      ./entrypoint.sh
    environment:
      - CELERY_BROKER=redis://redis:6379/0
    depends_on:
      - db
      - adminer
      - redis


  redis:
      image: redis
      ports:
        - 6379:6379


  celery:
    image: ticket_locator_img
    container_name: celery_container
    restart: always
    command: celery -A ticket_locator worker -l INFO
    environment:
      - CELERY_BROKER=redis://redis:6379/0
    depends_on:
      - db
      - web
      - redis


  db:
    image: postgres
    environment:
      POSTGRES_USER: ticket
      POSTGRES_DB: ticket_locator_db
      POSTGRES_PASSWORD: ticket
    ports:
    - 127.0.0.1:5432:5432


  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8080:8080