services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ticket
      POSTGRES_DB: ticket_locator_db
      POSTGRES_PASSWORD: ticket
    ports:
    - 127.0.0.1:5432:5432


  adminer:
    image: adminer
    ports:
      - 8080:8080

  redis:
    image: redis
    ports:
      - 8081:8081