# Generated by Django 3.2 on 2021-04-27 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('support', 'support'), ('user', 'user')], default='user', max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_city', models.CharField(max_length=128)),
                ('arrival_city', models.CharField(max_length=128)),
                ('depart_date', models.DateTimeField()),
                ('arrival_date', models.DateTimeField()),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_world.user')),
            ],
        ),
    ]
