# Generated by Django 3.2 on 2021-04-27 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('password', models.CharField(max_length=32)),
                ('active', models.BooleanField(default=False, verbose_name='Activity')),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_city', models.CharField(max_length=128, verbose_name='Departure city')),
                ('arrival_city', models.CharField(max_length=128, verbose_name='Arrival city')),
                ('departure_date', models.DateTimeField(verbose_name='Departure date')),
                ('arrival_date', models.DateTimeField(verbose_name='Arrival date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_world.user')),
            ],
        ),
    ]
