# Generated by Django 3.2 on 2021-04-26 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionsSet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('actions_set_name', models.CharField(max_length=250)),
                ('read', models.BooleanField()),
                ('write', models.BooleanField()),
                ('update', models.BooleanField()),
                ('create', models.BooleanField()),
                ('delete', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=90)),
                ('actions_set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='actions_set', to='hello_world.actionsset')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='user id')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='user email')),
                ('password', models.CharField(max_length=256, verbose_name='password hash')),
                ('active', models.BooleanField(default=True, verbose_name='active status')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_id', to='hello_world.userrole')),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('depart_city', models.CharField(max_length=250)),
                ('arrival_city', models.CharField(max_length=250)),
                ('depart_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='hello_world.user')),
            ],
        ),
    ]
