# Generated by Django 3.2 on 2021-04-26 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionsset',
            old_name='create',
            new_name='on_create',
        ),
        migrations.RenameField(
            model_name='actionsset',
            old_name='delete',
            new_name='on_delete',
        ),
        migrations.RenameField(
            model_name='actionsset',
            old_name='read',
            new_name='on_read',
        ),
        migrations.RenameField(
            model_name='actionsset',
            old_name='update',
            new_name='on_update',
        ),
        migrations.RenameField(
            model_name='actionsset',
            old_name='write',
            new_name='on_write',
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='hello_world.user'),
        ),
    ]
