# Generated by Django 3.2 on 2021-05-01 19:44

from django.db import migrations, models
import users_accounts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='user id')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='user email')),
                ('password', models.CharField(max_length=256, verbose_name='password')),
                ('is_active', models.BooleanField(default=True, verbose_name='active status')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
                ('is_admin', models.BooleanField(default=False, verbose_name='admin')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', users_accounts.models.CustomUserManager()),
            ],
        ),
    ]
