# Generated by Django 3.2 on 2021-05-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('depart_city', models.CharField(max_length=250)),
                ('arrival_city', models.CharField(max_length=250)),
                ('depart_date', models.DateField()),
                ('arrival_date', models.DateField()),
            ],
        ),
    ]
